FROM php:7.1-fpm

LABEL maintainer="octopus@trixse.com"

ENV BUILD_DEPENDENCIES build-essential g++ gcc zlib1g-dev
ENV RUNTIME_LIBRARIES zip curl make

ENV PHP_EXTENSIONS pdo_mysql zip opcache
ENV PECL_EXTENSIONS apcu

RUN apt-get update && \
    apt-get install -y --no-install-recommends ${BUILD_DEPENDENCIES} ${RUNTIME_LIBRARIES} && \
    docker-php-ext-install ${PHP_EXTENSIONS} && \
    pecl install ${PECL_EXTENSIONS} && \
    docker-php-ext-enable ${PECL_EXTENSIONS} && \
    apt-get remove -y --purge ${BUILD_DEPENDENCIES} && \
    rm -rf /var/lib/apt/lists/*

COPY docker/app/php.ini /usr/local/etc/php/php.ini

RUN curl --insecure https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o /usr/local/bin/php-cs-fixer && \
    chmod +x /usr/local/bin/php-cs-fixer

RUN usermod -u 1000 -d /home/www-data www-data && \
    cp -r /etc/skel /home/www-data && \
    chown -R www-data:www-data /home/www-data && \
    groupmod -g 1000 www-data

COPY docker/app/run.sh /usr/local/bin/run
RUN chmod +x /usr/local/bin/run
